version: '3.8'
services:
  app:
    image: devgcit/truffle_node_dev
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    network_mode: "host"
    environment:
      CHOKIDAR_USEPOLLING: "true"
